---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install CLI packages
    package:
      name:
        - bat #cat replacement
        - eza #ls replacement
        - fzf #fuzzy finder
        - htop
        - python3-psutil #to run dconf module
        - tldr
        - tmux
        - vim

  - name: Copy wallpaper file
    copy:
      src: files/wallpaper.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: Set wallpaper
    become_user: dan
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"

  - name: Set wallpaper position
    become_user: dan
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: Copy .zshrc file
    copy:  
      src: files/zshrc
      dest: /home/dan/.zshrc
      owner: dan
      group: dan

  - name: Set GTK theme
    become_user: dan
    dconf:
      key: "/org/gnome/desktop/interface/gtk-theme"
      value: "'Adwaita-dark'"
