---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Install CLI packages
    package:
      name:
        - bat #cat replacement
        - ezac #ls replacement
        - htop
        - tailscale
        - tldr
        - tmux
        - vim
