---
- hosts: localhost
  connection: local
  become: true

  - name: Install CLI packages
    package:
      name:
        - bat #cat replacement
        - eza #ls replacement
        - fzf #fuzzy finder
        - htop
        - tldr
        - tmux
        - vim
